CREATE TYPE "job_status" AS ENUM (
  'new',
  'reviewing',
  'awaiting_dispatch',
  'dispatching',
  'accepted',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE "partner_status" AS ENUM (
  'pending',
  'approved',
  'rejected',
  'suspended'
);

CREATE TYPE "dispatch_state" AS ENUM (
  'pending',
  'accepted',
  'declined',
  'expired',
  'cancelled'
);

CREATE TABLE "jobs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference" varchar(32) NOT NULL,
  "description" text NOT NULL,
  "trade" text NOT NULL,
  "suburb" text NOT NULL,
  "postcode" varchar(16) NOT NULL,
  "urgency" text NOT NULL,
  "preferred_time" text NOT NULL,
  "status" "job_status" NOT NULL DEFAULT 'awaiting_dispatch',
  "customer_name" text NOT NULL,
  "customer_phone" text,
  "customer_email" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "job_images" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "image_name" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "job_status_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "from_status" "job_status",
  "to_status" "job_status" NOT NULL,
  "note" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "partners" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_name" text NOT NULL,
  "contact_name" text NOT NULL,
  "abn" text,
  "trade" text NOT NULL,
  "licence" text,
  "mobile" text NOT NULL,
  "email" text NOT NULL,
  "radius_km" integer NOT NULL DEFAULT 15,
  "emergency_jobs" boolean NOT NULL DEFAULT false,
  "availability" boolean NOT NULL DEFAULT false,
  "status" "partner_status" NOT NULL DEFAULT 'pending',
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "partner_service_areas" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partner_id" integer NOT NULL REFERENCES "partners"("id") ON DELETE CASCADE,
  "suburb" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "partner_services" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "partner_id" integer NOT NULL REFERENCES "partners"("id") ON DELETE CASCADE,
  "service" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE "dispatch_offers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "partner_id" integer NOT NULL REFERENCES "partners"("id") ON DELETE CASCADE,
  "state" "dispatch_state" NOT NULL DEFAULT 'pending',
  "offered_at" timestamp with time zone NOT NULL DEFAULT now(),
  "responded_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "jobs_reference_uidx" ON "jobs" ("reference");
CREATE INDEX "jobs_status_idx" ON "jobs" ("status");
CREATE INDEX "jobs_created_at_idx" ON "jobs" ("created_at");

CREATE INDEX "job_images_job_id_idx" ON "job_images" ("job_id");
CREATE UNIQUE INDEX "job_images_job_id_name_uidx" ON "job_images" ("job_id", "image_name");

CREATE INDEX "job_status_history_job_id_idx" ON "job_status_history" ("job_id");
CREATE INDEX "job_status_history_created_at_idx" ON "job_status_history" ("created_at");

CREATE INDEX "partners_status_idx" ON "partners" ("status");
CREATE INDEX "partners_availability_idx" ON "partners" ("availability");

CREATE UNIQUE INDEX "partner_service_areas_partner_suburb_uidx" ON "partner_service_areas" ("partner_id", "suburb");
CREATE INDEX "partner_service_areas_partner_id_idx" ON "partner_service_areas" ("partner_id");

CREATE UNIQUE INDEX "partner_services_partner_service_uidx" ON "partner_services" ("partner_id", "service");
CREATE INDEX "partner_services_partner_id_idx" ON "partner_services" ("partner_id");

CREATE INDEX "dispatch_offers_job_id_idx" ON "dispatch_offers" ("job_id");
CREATE INDEX "dispatch_offers_partner_id_idx" ON "dispatch_offers" ("partner_id");
CREATE INDEX "dispatch_offers_state_idx" ON "dispatch_offers" ("state");