CREATE TYPE "app_role" AS ENUM ('partner', 'admin');

CREATE TABLE "app_users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auth_user_id" uuid NOT NULL,
  "role" "app_role" NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX "app_users_auth_user_id_uidx" ON "app_users" ("auth_user_id");
CREATE INDEX "app_users_role_idx" ON "app_users" ("role");
CREATE INDEX "app_users_active_idx" ON "app_users" ("is_active");

ALTER TABLE "partners" ADD COLUMN "auth_user_id" uuid;
CREATE UNIQUE INDEX "partners_auth_user_id_uidx" ON "partners" ("auth_user_id");

ALTER TABLE "jobs" ADD COLUMN "public_status_token" varchar(64);

UPDATE "jobs"
SET "public_status_token" = md5(id::text || random()::text || clock_timestamp()::text)
  || md5(random()::text || clock_timestamp()::text || id::text)
WHERE "public_status_token" IS NULL;

ALTER TABLE "jobs" ALTER COLUMN "public_status_token" SET NOT NULL;
CREATE UNIQUE INDEX "jobs_public_status_token_uidx" ON "jobs" ("public_status_token");
