CREATE TABLE "job_intake_submissions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "customer_confirmed_values" jsonb NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "job_intake_submissions_job_id_idx" ON "job_intake_submissions" ("job_id");
--> statement-breakpoint
CREATE INDEX "job_intake_submissions_created_at_idx" ON "job_intake_submissions" ("created_at");
--> statement-breakpoint
CREATE TABLE "job_ai_assessments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "submission_id" integer NOT NULL REFERENCES "job_intake_submissions"("id") ON DELETE CASCADE,
  "provider" text NOT NULL,
  "model" text,
  "outcome" text NOT NULL,
  "safety_codes" jsonb NOT NULL,
  "assessment" jsonb NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "job_ai_assessments_job_id_idx" ON "job_ai_assessments" ("job_id");
--> statement-breakpoint
CREATE INDEX "job_ai_assessments_submission_id_idx" ON "job_ai_assessments" ("submission_id");
--> statement-breakpoint
CREATE INDEX "job_ai_assessments_created_at_idx" ON "job_ai_assessments" ("created_at");
--> statement-breakpoint
CREATE OR REPLACE FUNCTION "prevent_phase4_intake_mutation"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Phase 4 intake and AI assessment records are append-only';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "job_intake_submissions_immutable"
BEFORE UPDATE OR DELETE ON "job_intake_submissions"
FOR EACH ROW EXECUTE FUNCTION "prevent_phase4_intake_mutation"();
--> statement-breakpoint
CREATE TRIGGER "job_ai_assessments_append_only"
BEFORE UPDATE OR DELETE ON "job_ai_assessments"
FOR EACH ROW EXECUTE FUNCTION "prevent_phase4_intake_mutation"();
