ALTER TABLE "jobs" ADD COLUMN "service_address_line_1" text;
ALTER TABLE "jobs" ADD COLUMN "service_address_line_2" text;
ALTER TABLE "dispatch_offers" ADD COLUMN "eta" text;

CREATE TYPE "notification_status" AS ENUM ('pending', 'sent', 'delivered', 'failed');
CREATE TABLE "notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "dispatch_offer_id" integer REFERENCES "dispatch_offers"("id") ON DELETE CASCADE,
  "recipient_type" text NOT NULL,
  "type" text NOT NULL,
  "channel" text NOT NULL DEFAULT 'email',
  "status" "notification_status" NOT NULL DEFAULT 'pending',
  "idempotency_key" text NOT NULL,
  "provider_message_id" text,
  "error_code" text,
  "sent_at" timestamp with time zone,
  "delivered_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "notifications_idempotency_key_uidx" ON "notifications" ("idempotency_key");
CREATE INDEX "notifications_job_id_idx" ON "notifications" ("job_id");
CREATE INDEX "notifications_dispatch_offer_id_idx" ON "notifications" ("dispatch_offer_id");
CREATE INDEX "notifications_status_idx" ON "notifications" ("status");
