ALTER TABLE partners
  ADD COLUMN IF NOT EXISTS acquisition_utm_source text,
  ADD COLUMN IF NOT EXISTS acquisition_utm_medium text,
  ADD COLUMN IF NOT EXISTS acquisition_utm_campaign text;

CREATE TABLE IF NOT EXISTS partner_funnel_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL,
  event_type text NOT NULL CHECK (
    event_type IN ('partner_page_viewed', 'partner_application_started', 'partner_application_submitted')
  ),
  application_submission_id uuid,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE partner_funnel_events ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS partner_funnel_events_session_event_uidx
  ON partner_funnel_events (session_id, event_type);
CREATE INDEX IF NOT EXISTS partner_funnel_events_created_at_idx
  ON partner_funnel_events (created_at);
CREATE INDEX IF NOT EXISTS partner_funnel_events_campaign_idx
  ON partner_funnel_events (utm_campaign);
