CREATE TABLE IF NOT EXISTS "homeowner_funnel_events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" uuid NOT NULL,
  "event_type" text NOT NULL,
  "job_id" integer REFERENCES "jobs"("id") ON DELETE SET NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "homeowner_funnel_events_session_event_uidx" ON "homeowner_funnel_events" ("session_id", "event_type");
CREATE INDEX IF NOT EXISTS "homeowner_funnel_events_job_id_idx" ON "homeowner_funnel_events" ("job_id");
CREATE INDEX IF NOT EXISTS "homeowner_funnel_events_created_at_idx" ON "homeowner_funnel_events" ("created_at");

CREATE TABLE IF NOT EXISTS "candidate_providers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "business_name" text NOT NULL,
  "contact_name" text,
  "trade" text NOT NULL,
  "sub_services" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "phone" text NOT NULL,
  "website" text,
  "service_suburbs" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "service_postcodes" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "normal_hours" text,
  "after_hours_available" boolean NOT NULL DEFAULT false,
  "licence_details" text,
  "licence_status" text NOT NULL DEFAULT 'not_checked',
  "insurance_status" text NOT NULL DEFAULT 'not_checked',
  "source" text NOT NULL,
  "verification_status" text NOT NULL DEFAULT 'candidate',
  "outreach_status" text NOT NULL DEFAULT 'not_contacted',
  "last_contact_at" timestamptz,
  "opted_out_at" timestamptz,
  "response_count" integer NOT NULL DEFAULT 0,
  "acceptance_count" integer NOT NULL DEFAULT 0,
  "tier" text NOT NULL DEFAULT 'candidate',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "candidate_providers_phone_uidx" ON "candidate_providers" ("phone");
CREATE INDEX IF NOT EXISTS "candidate_providers_trade_idx" ON "candidate_providers" ("trade");
CREATE INDEX IF NOT EXISTS "candidate_providers_outreach_idx" ON "candidate_providers" ("outreach_status");

CREATE TABLE IF NOT EXISTS "provider_outreach_attempts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "candidate_provider_id" integer REFERENCES "candidate_providers"("id") ON DELETE RESTRICT,
  "partner_id" integer REFERENCES "partners"("id") ON DELETE RESTRICT,
  "channel" text NOT NULL DEFAULT 'sms',
  "status" text NOT NULL DEFAULT 'queued',
  "provider_message_id" text,
  "response_code" text,
  "response_payload" jsonb,
  "idempotency_key" text NOT NULL,
  "timeout_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "provider_outreach_exactly_one_provider" CHECK (((candidate_provider_id IS NOT NULL)::integer + (partner_id IS NOT NULL)::integer) = 1)
);
CREATE UNIQUE INDEX IF NOT EXISTS "provider_outreach_attempts_idempotency_uidx" ON "provider_outreach_attempts" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "provider_outreach_one_active_per_job_uidx" ON "provider_outreach_attempts" ("job_id") WHERE "status" IN ('queued', 'sent', 'awaiting_response', 'accepted');
CREATE INDEX IF NOT EXISTS "provider_outreach_attempts_job_idx" ON "provider_outreach_attempts" ("job_id");

CREATE TABLE IF NOT EXISTS "operational_settings" (
  "key" text PRIMARY KEY,
  "value" jsonb NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
INSERT INTO "operational_settings" ("key", "value") VALUES
  ('sourcing_timeouts_minutes', '{"ASAP":10,"Today":30,"This week":240,"Flexible":720}'::jsonb),
  ('booking_fee', '{"enabled":false,"amountCents":null,"label":"Secure Booking Fee","refundWhenServiceNotProvided":true}'::jsonb)
ON CONFLICT ("key") DO NOTHING;
