DO $$ BEGIN
  CREATE TYPE "paid_flow_state" AS ENUM (
    'not_started',
    'serviceable',
    'manual_review',
    'unsupported',
    'checkout_started',
    'payment_confirmed',
    'sourcing',
    'match_ready',
    'approved',
    'completed',
    'sourcing_failed',
    'refund_pending',
    'refunded'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "paid_flow_state" "paid_flow_state" NOT NULL DEFAULT 'not_started';
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "serviceability_checked_at" timestamptz;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "serviceability_reason" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_name" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_phone" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_price_min_cents" integer;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_price_max_cents" integer;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_eta" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_provider_notes" text;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "matched_at" timestamptz;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "approved_at" timestamptz;

CREATE INDEX IF NOT EXISTS "jobs_paid_flow_state_idx" ON "jobs" ("paid_flow_state");

CREATE TABLE IF NOT EXISTS "job_payments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL REFERENCES "jobs"("id") ON DELETE CASCADE,
  "stripe_checkout_session_id" text,
  "stripe_payment_intent_id" text,
  "stripe_customer_id" text,
  "stripe_refund_id" text,
  "amount_cents" integer NOT NULL DEFAULT 2999,
  "currency" text NOT NULL DEFAULT 'aud',
  "status" text NOT NULL DEFAULT 'pending',
  "idempotency_key" text NOT NULL,
  "test_mode" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "paid_at" timestamptz,
  "refunded_at" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "job_payments_idempotency_uidx" ON "job_payments" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "job_payments_checkout_session_uidx" ON "job_payments" ("stripe_checkout_session_id") WHERE "stripe_checkout_session_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "job_payments_job_id_idx" ON "job_payments" ("job_id");
CREATE INDEX IF NOT EXISTS "job_payments_status_idx" ON "job_payments" ("status");
ALTER TABLE "job_payments" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS "job_payment_events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stripe_event_id" text NOT NULL,
  "job_id" integer REFERENCES "jobs"("id") ON DELETE SET NULL,
  "type" text NOT NULL,
  "payload" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "job_payment_events_stripe_event_uidx" ON "job_payment_events" ("stripe_event_id");
CREATE INDEX IF NOT EXISTS "job_payment_events_job_id_idx" ON "job_payment_events" ("job_id");
ALTER TABLE "job_payment_events" ENABLE ROW LEVEL SECURITY;
