CREATE TABLE IF NOT EXISTS "candidate_provider_trades" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candidate_provider_id" integer NOT NULL REFERENCES "candidate_providers"("id") ON DELETE CASCADE,
  "trade" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "candidate_provider_trades_provider_trade_uidx" ON "candidate_provider_trades" ("candidate_provider_id", "trade");
CREATE INDEX IF NOT EXISTS "candidate_provider_trades_trade_idx" ON "candidate_provider_trades" ("trade");
CREATE INDEX IF NOT EXISTS "candidate_provider_trades_provider_id_idx" ON "candidate_provider_trades" ("candidate_provider_id");
ALTER TABLE "candidate_provider_trades" ENABLE ROW LEVEL SECURITY;

-- Backfill: every existing candidate_providers row gets a capability row for
-- its current single trade. Idempotent (safe to re-run) and a no-op today
-- since Production has zero candidate_providers rows.
INSERT INTO "candidate_provider_trades" ("candidate_provider_id", "trade")
SELECT "id", "trade" FROM "candidate_providers"
ON CONFLICT ("candidate_provider_id", "trade") DO NOTHING;
